### ISSUE TITLE
de/v2.2.4

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/riot.github.io#21]
Issue for translating the website to german.
I'd love to invite @whazap to have a look on riotjs and contribute if possible.

**TODO**
- [x] Finding labels for most of the nav-items, most of them are anglicism. (router, compiler, etc.)
- [ ] API - 
- [ ] Merging Master commits
- [x] finding a proper name for "custom tag" - "eigener Tag"? 
- [x] Common layouts and includes
- [x] index.md
- [x] forum.md
- [x] faq.md
- [x] download.md
- [ ] compare.md
- [ ] guide
  - [ ] index.md
  - [x] application-design.md
  - [ ] compiler.md
- [ ] api
  - [ ] compiler.md
  - [ ] index.md
  - [x] misc.md
  - [x] observerable.md
  - [ ] route.md

Meanwhile: check out my fork: https://github.com/MartinMuzatko/riot.github.io/tree/riot/de/v2.2.4

**Comment by cognitom** [comment]
:+1:

**Comment by tipiirai** [comment]
So glad to see all these translations popping up!

**Comment by cognitom** [comment]
@MartinMuzatko as mentioned on another issue, no need to translate "Guide - v1.0.md".

**Comment by MartinMuzatko** [comment]
Yep, understood :)

**Comment by MartinMuzatko** [comment]
I'm only progressing slowly. I couldn't find anyone to help me so far, so it will take a bit longer than expected. Sorry for that @cognitom.

**Comment by cognitom** [comment]
Don't worry! No rush ;-)

**Comment by GianlucaGuarini** [comment]
closing this issue due to inactivity
